# ~/.zshenv: executed by the command interpreter for all shells

# Fix gnome-terminal color support
if [[ "$COLORTERM" == "gnome-terminal" ]] ; then
  if [[ "$TERM" == "xterm" ]] ; then
    TERM="xterm-256color"
  elif [[ "$TERM" == "screen" ]] ; then
    TERM="screen-256color"
  fi
fi

# Make sure everyone knows I use vim
EDITOR=`which vim`
VISUAL=`which vim`
# # Try using Spacemacs for a while
# export ALTERNATE_EDITOR=""
# export EDITOR=emacsclient

######
# Everything below here must be exported.
#####

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Update PATH for the Google Cloud SDK.
source "$HOME/.local/share/google-cloud-sdk/path.zsh.inc"

# Update PATH for fzf.
if [[ ! "$PATH" == *$HOME/.local/share/fzf/bin* ]]; then
  export PATH="$PATH:$HOME/.local/share/fzf/bin"
fi

# Set up go
if [[ ! "$PATH" == */usr/local/go/bin* ]]; then
  PATH="$PATH:/usr/local/go/bin"
fi

if [[ ! "$PATH" == *$HOME/.local/share/depot_tools* ]]; then
  PATH="$PATH:$HOME/.local/share/depot_tools"
fi

export PATH

# Necessary for https://github.com/FiloSottile/yubikey-agent
export SSH_AUTH_SOCK="/usr/local/var/run/yubikey-agent.sock"

