# ~/.zshenv: executed by the command interpreter for all shells

# Fix gnome-terminal color support
if [[ "$COLORTERM" == "gnome-terminal" ]] ; then
  if [[ "$TERM" == "xterm" ]] ; then
    TERM="xterm-256color"
  elif [[ "$TERM" == "screen" ]] ; then
    TERM="screen-256color"
  fi
fi

# Make sure everyone knows I use vim
EDITOR=`which vim`
VISUAL=`which vim`

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

PATH="$HOME/bin/depot_tools:$PATH"
PATH="$HOME/bin/gsutil:$PATH"
PATH="$HOME/bin/google_appengine:$PATH"

MANPATH=":$HOME/bin/depot_tools/docs"
export MANPATH
