# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
ZSH_THEME="mytheme"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git history-substring-search python screen tmux vundle vi-mode zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# If ssh keys haven't been added to the ssh-agent already, do so now.
# Due to $ZSH/custom/sshag.zsh, they will be persistent across all other
# terminals spawned after this one.
# if [[ $(ssh-add -l) == "The agent has no identities." ]] ; then
#   ssh-add $HOME/.ssh/id_rsa
# fi

# Vim FTW.
bindkey -a 'v' edit-command-line
bindkey '' backward-delete-char
bindkey '' backward-kill-word

# Autocompletion for commands in the Chromium infra repositories.
autoload -Uz bashcompinit compinit
bashcompinit
eval "$($HOME/work/infra/infra/ENV/bin/register-python-argcomplete run.py)"
eval "$($HOME/work/infra/infra/ENV/bin/register-python-argcomplete test.py)"

# The next line enables bash completion for gcloud.
source "$HOME/local/bin/google-cloud-sdk/completion.zsh.inc"
source /etc/bash_completion.d/g4d
